# Generated by Django 6.0 on 2025-12-22 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("host", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField(default=8001)),
                (
                    "capacity",
                    models.BigIntegerField(help_text="Total capacity in bytes"),
                ),
                (
                    "available",
                    models.BigIntegerField(help_text="Available space in bytes"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_heartbeat", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Storage Node",
                "verbose_name_plural": "Storage Nodes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "size",
                    models.BigIntegerField(
                        db_index=True, help_text="File size in bytes"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 checksum of the file",
                        max_length=64,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "checksum",
                    models.CharField(help_text="SHA-256 checksum", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="storage.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Version",
                "verbose_name_plural": "File Versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_number", models.PositiveIntegerField(db_index=True)),
                ("size", models.PositiveIntegerField(help_text="Chunk size in bytes")),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum of the chunk", max_length=64
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the primary copy",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("completed", "Completed"),
                            ("corrupted", "Corrupted"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="uploading",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="storage.file",
                    ),
                ),
                (
                    "storage_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="storage.storagenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Chunk",
                "verbose_name_plural": "File Chunks",
                "ordering": ["chunk_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                fields=("name", "checksum", "user"),
                name="unique_file_name_checksum_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("file", "chunk_number", "storage_node")},
        ),
    ]
