# Generated by Cascade on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="object_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Node-local identifier/path to the stored chunk bytes",
                max_length=512,
            ),
        ),
    ]
